// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agygqxctpnhkrtqvlqpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFneWdxeGN0cG5oa3J0cXZscXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjEwMDYsImV4cCI6MjA2NDE5NzAwNn0.PxM2u7hquy2sUDNEovZ9kR2_-A7P0CKCD4yECpFaCsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);